//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservas
    {
        public int idreserva { get; set; }
        public Nullable<int> idpt { get; set; }
        public Nullable<int> idcli { get; set; }
        public Nullable<System.DateTime> datainicio { get; set; }
        public Nullable<System.DateTime> datafinal { get; set; }
        public Nullable<int> tempo { get; set; }
        public Nullable<decimal> custo { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual trainers trainers { get; set; }
    }
}
